version: "3.8"

services:
  php:
    image: php:7.4-apache
    container_name: php
    cpus: "0.5"
    mem_limit: 200m
    volumes:
        - ./src:/var/www/html
    ports:
        - "${VKRSS_PORT}:9900"
    networks:
      - caddy
    restart: unless-stopped

networks:
  caddy:
    external: true